# Generated by Django 4.0.3 on 2022-05-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_user_ticket_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('InProgess', 'InProgess'), ('Resolved', 'Resolved')], default='Open', max_length=200, null=True),
        ),
    ]
